### ISSUE TITLE
Is there a way to specify a class using React Object.

### ISSUE THREAD

**Issue by sittim** [MrEbbinghaus/fulcro-material-ui-wrapper#2]
For example, looking at the page:

https://material-ui.com/components/avatars/

You can specify the avatar color by: `<Avatar className={classes.orange}>N</Avatar>` but how do you specify the `className` in CLJS?

**Comment by MrEbbinghaus** [comment]
`(mui/avatar {:className "my-class"})`

The stuff in the curly braces is JavaScript that gets evaluated. 

https://github.com/sittim/fulcro-material-ui-wrapper/blob/master/README.md


Maybe you can use this:
```clojure
(def ColoredAvatar
  (js/React.forwardRef
    (fn [props ref]
      (let [{:keys [color children] :as props} (js->clj props :keywordize-keys true)
            get-contrast-text (get-in (styles/use-theme) [:palette :getContrastText])]
        (apply dd/avatar
          (-> props
            (assoc :ref ref)
            (update :style
              assoc
              :backgroundColor color
              :color (get-contrast-text color)))
          children)))))
          
(def ui-colored-avatar (interop/react-factory ColoredAvatar))


(ui-colored-avatar {:color "#FF00FF"} "S")
```
From: https://github.com/hhucn/decide3/blob/master/src/main/decide/models/user/ui.cljs#L21
